### ISSUE TITLE
Autocomplete for @mentions

### ISSUE THREAD

**Issue by pugson** [jonathontoon/tweet-tray#78] opened 2018-02-07 17:46 UTC
Would be great to have autocomplete when mentioning someone just like Twitter.

<img width="401" alt="screen shot 2018-02-07 at 6 45 58 pm" src="https://user-images.githubusercontent.com/6843656/35932137-33b1606a-0c37-11e8-83dc-ff1929846b64.png">

**Comment by jonathontoon** [comment] 2018-02-07 22:43
Thanks for the suggestion. Marking this as a duplicate of #34 for now.

**Closed** 2018-02-07 22:43 UTC
Labels: duplicate

**Comment by joeflateau** [comment] 2018-03-28 18:29
@jonathontoon just arrived here after trying to @ someone in Tweet Tray... I noticed you marked this as a duplicate of "When Settings overlay is clicked dismiss the component". Perhaps you meant a different issue? This is very different from dismissing.

**Comment by jonathontoon** [comment] 2018-03-28 22:59
Oops, thanks @joeflateau.
